language: generic
sudo: false

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis

  include:
    - os: linux
      sudo: false
      env: EVM_EMACS=emacs-25.1-travis
    - os: linux
      sudo: false
      env: EVM_EMACS=emacs-git-snapshot-travis
    - os: osx
      sudo: false

install:
  - ./travis-install.sh
    
script:
  - emacs --version -l init.el
  - make build
  - make test
