language: generic
sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pwd; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./scimax/install-scimax-mac.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then evm install $EVM_EMACS --use --skip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cask; fi

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis

  include:
    - os: linux
      sudo: false
      env: EVM_EMACS=emacs-25.1-travis
    - os: linux
      sudo: false
      env: EVM_EMACS=emacs-git-snapshot-travis
    - os: osx
      sudo: false
    
script:
  - emacs --version -l init.el
  - make build
  - make test
